CREATE TABLE "users" (
	"avatar" text NOT NULL,
	"country" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"dob" timestamp with time zone NOT NULL,
	"email" text NOT NULL,
	"email_verified_at" timestamp with time zone,
	"first_name" text NOT NULL,
	"gender" text NOT NULL,
	"google_id" text,
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"is_suspended" boolean DEFAULT false NOT NULL,
	"last_login_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_name" text NOT NULL,
	"login_retry_count" integer DEFAULT 0 NOT NULL,
	"medical_certificate" text,
	"password_hash" text NOT NULL,
	"refresh_token_array" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"role" text NOT NULL,
	"specialty" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
