services:
   medinfo-postgres-db:
      image: postgres:18-alpine
      container_name: medinfo-postgres-db
      restart: unless-stopped
      env_file:
         - ./apps/backend/.env
      ports:
         - 5432:5432
      volumes:
         - medinfo-postgres-db-data:/var/lib/postgresql/data
      networks:
         - medinfo-network
      healthcheck:
         test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB]
         interval: 10s
         timeout: 5s
         retries: 3

   medinfo-redis-cache:
      image: redis:8
      container_name: medinfo-redis-cache
      restart: unless-stopped
      ports:
         - 6379:6379
      networks:
         - medinfo-network
      healthcheck:
         test: [CMD, redis-cli, ping]
         interval: 10s
         timeout: 5s
         retries: 3

   #  medinfo-redis-queue:
   #     image: redis:8
   #     container_name: medinfo-redis-queue
   #     restart: unless-stopped
   #     ports:
   #        - 6381:6381
   #     networks:
   #        - medinfo-network
   #     healthcheck:
   #        test: [CMD, redis-cli, ping]
   #        interval: 10s
   #        timeout: 5s
   #        retries: 3

   medinfo-backend:
      build:
         context: .
         dockerfile: apps/backend/Dockerfile
      container_name: medinfo-backend
      restart: unless-stopped
      depends_on:
         medinfo-postgres-db:
            condition: service_healthy
         medinfo-redis-cache:
            condition: service_healthy
         medinfo-redis-queue:
            condition: service_healthy
      networks:
         - medinfo-network
      ports:
         - 8000:8000
      env_file:
         - ./apps/backend/.env
      environment:
         - DATABASE_URL_DEV=postgresql://postgres:postgres@medinfo-postgres-db:5432/medinfo
         - REDIS_CACHE_URL_DEV=redis://medinfo-redis-cache:6379
         - REDIS_QUEUE_URL_DEV=redis://medinfo-redis-queue:6379

      healthcheck:
         test: [CMD, wget, --no-verbose, --tries=1, --spider, http://localhost:8000]
         interval: 30s
         timeout: 3s
         start_period: 10s
         retries: 3

volumes:
   medinfo-postgres-db-data:

networks:
   medinfo-network:
